# Generated by cpp11: do not edit by hand

c_cumema <- function(X, days, n) {
  .Call(`_iroll_c_cumema`, X, days, n)
}

c_ema <- function(X, days, n) {
  .Call(`_iroll_c_ema`, X, days, n)
}

c_ema_lin <- function(X, days, n) {
  .Call(`_iroll_c_ema_lin`, X, days, n)
}

c_ediversity <- function(X, N, n) {
  .Call(`_iroll_c_ediversity`, X, N, n)
}

c_cum_unique_count <- function(X, N) {
  .Call(`_iroll_c_cum_unique_count`, X, N)
}

c_roll_min <- function(ix, X, left_bound, right_bound, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_min`, ix, X, left_bound, right_bound, left_open, right_open, fill)
}

c_roll_max <- function(ix, X, left_bound, right_bound, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_max`, ix, X, left_bound, right_bound, left_open, right_open, fill)
}

c_roll_mean <- function(ix, X, left_bound, right_bound, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_mean`, ix, X, left_bound, right_bound, left_open, right_open, fill)
}

c_roll_sd <- function(ix, X, left_bound, right_bound, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_sd`, ix, X, left_bound, right_bound, left_open, right_open, fill)
}

c_roll_sum <- function(ix, X, left_bound, right_bound, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_sum`, ix, X, left_bound, right_bound, left_open, right_open, fill)
}

c_roll_prod <- function(ix, X, left_bound, right_bound, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_prod`, ix, X, left_bound, right_bound, left_open, right_open, fill)
}

c_roll_first <- function(ix, X, left_bound, right_bound, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_first`, ix, X, left_bound, right_bound, left_open, right_open, fill)
}

c_roll_last <- function(ix, X, left_bound, right_bound, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_last`, ix, X, left_bound, right_bound, left_open, right_open, fill)
}

c_roll_quantile <- function(ix, X, left_bound, right_bound, left_open, right_open, prob, fill) {
  .Call(`_iroll_c_roll_quantile`, ix, X, left_bound, right_bound, left_open, right_open, prob, fill)
}

c_cummin <- function(X) {
  .Call(`_iroll_c_cummin`, X)
}

c_cummax <- function(X) {
  .Call(`_iroll_c_cummax`, X)
}
