# Generated by cpp11: do not edit by hand

c_cumema <- function(X, days, n) {
  .Call(`_iroll_c_cumema`, X, days, n)
}

c_ema <- function(X, days, n) {
  .Call(`_iroll_c_ema`, X, days, n)
}

c_ema_lin <- function(X, days, n) {
  .Call(`_iroll_c_ema_lin`, X, days, n)
}

c_ediversity <- function(X, N, n) {
  .Call(`_iroll_c_ediversity`, X, N, n)
}

c_cum_unique_count <- function(X, N) {
  .Call(`_iroll_c_cum_unique_count`, X, N)
}

c_roll_min <- function(X, ix, left, right, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_min`, X, ix, left, right, left_open, right_open, fill)
}

c_roll_max <- function(X, ix, left, right, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_max`, X, ix, left, right, left_open, right_open, fill)
}

c_roll_first <- function(X, ix, left, right, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_first`, X, ix, left, right, left_open, right_open, fill)
}

c_roll_last <- function(X, ix, left, right, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_last`, X, ix, left, right, left_open, right_open, fill)
}

c_roll_mean <- function(X, ix, left, right, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_mean`, X, ix, left, right, left_open, right_open, fill)
}

c_roll_sd <- function(X, ix, left, right, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_sd`, X, ix, left, right, left_open, right_open, fill)
}

c_roll_sum <- function(X, ix, left, right, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_sum`, X, ix, left, right, left_open, right_open, fill)
}

c_roll_prod <- function(X, ix, left, right, left_open, right_open, fill) {
  .Call(`_iroll_c_roll_prod`, X, ix, left, right, left_open, right_open, fill)
}

c_roll_quantile <- function(X, ix, left, right, left_open, right_open, prob, fill) {
  .Call(`_iroll_c_roll_quantile`, X, ix, left, right, left_open, right_open, prob, fill)
}

c_cummin <- function(X) {
  .Call(`_iroll_c_cummin`, X)
}

c_cummax <- function(X) {
  .Call(`_iroll_c_cummax`, X)
}
