# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_cumema <- function(X, days, n) {
    .Call(`_iroll_c_cumema`, X, days, n)
}

c_ema <- function(X, days, n) {
    .Call(`_iroll_c_ema`, X, days, n)
}

c_ema_lin <- function(X, days, n) {
    .Call(`_iroll_c_ema_lin`, X, days, n)
}

c_ediversity <- function(X, N, n) {
    .Call(`_iroll_c_ediversity`, X, N, n)
}

c_cum_unique_count <- function(X, N) {
    .Call(`_iroll_c_cum_unique_count`, X, N)
}

#' @export
c_roll_min <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_iroll_c_roll_min`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_max <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_iroll_c_roll_max`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_mean <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_iroll_c_roll_mean`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_sd <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_iroll_c_roll_sd`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_sum <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_iroll_c_roll_sum`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_prod <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_iroll_c_roll_prod`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_first <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_iroll_c_roll_first`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_last <- function(DATE, X, left_bound, right_bound, left_open, right_open) {
    .Call(`_iroll_c_roll_last`, DATE, X, left_bound, right_bound, left_open, right_open)
}

#' @export
c_roll_quantile <- function(DATE, X, left_bound, right_bound, left_open, right_open, prob) {
    .Call(`_iroll_c_roll_quantile`, DATE, X, left_bound, right_bound, left_open, right_open, prob)
}

#' @export
c_cummin <- function(X) {
    .Call(`_iroll_c_cummin`, X)
}

#' @export
c_cummax <- function(X) {
    .Call(`_iroll_c_cummax`, X)
}

